window.SITE_CONFIG={
 site:{name:'Puja Mohapatra',title:'Clinical Psychologist',description:'A calm, thoughtful space for psychological support and wellbeing.'},
 professional:{name:'Puja Mohapatra',designation:'Clinical Psychologist',biography:'Add the verified professional biography here. Keep this section focused on professional background, areas of practice, and the values that guide the practice.',qualifications:'[Add verified qualifications]',registration:'[Add verified registration details]',experience:'[Add verified experience]'},
 hero:{eyebrow:'HEAL · GROW · THRIVE',heading:'Compassionate support for a',highlight:'healthier, more balanced you.',description:'I’m Puja Mohapatra, a Clinical Psychologist, dedicated to helping you understand your emotions, build resilience, and create meaningful change in your life.',image:'assets/hero-clean.jpg'},
 philosophy:'I listen without judgment and work collaboratively to understand the person behind the concern.',
 timeline:[{year:'[Year]',title:'Education / Professional Milestone',text:'Add verified details.'},{year:'[Year]',title:'Training / Experience',text:'Add verified details.'},{year:'[Year]',title:'Current Practice',text:'Add verified details.'}],
 services:[{title:'Individual Therapy',text:'Personalized support for anxiety, stress, self-esteem, and more.'},{title:'Family & Relationship Counselling',text:'Build healthier relationships and stronger connections.'},{title:'Child & Adolescent Therapy',text:'Support for emotional, behavioral, and academic challenges.'},{title:'Workplace Wellbeing',text:'Manage stress, improve focus, and create a healthier work-life balance.'}],
 process:[{number:'01',title:'Reach out',text:'Share a few basics and let the practice know what you are looking for.'},{number:'02',title:'First conversation',text:'Use the initial meeting to discuss concerns, goals, context, and fit.'},{number:'03',title:'A considered plan',text:'If the practice is an appropriate fit, next steps can be discussed together.'}],
approach:[{title:'Build self-awareness',text:'Understand thoughts, feelings, patterns, and personal context.'},{title:'Develop healthy coping skills',text:'Learn practical ways to respond to everyday challenges.'},{title:'Strengthen emotional resilience',text:'Build resources for steadier, more confident wellbeing.'},{title:'Create lasting change',text:'Work toward meaningful goals at a sustainable pace.'}],
 gallery:[{image:'assets/bg-practice.svg',title:'A calm setting',caption:'A considered visual space for reflection and conversation.'},{image:'assets/bg-about.svg',title:'Thoughtful details',caption:'Warm, quiet design cues that keep the practice feeling welcoming.'},{image:'assets/bg-journey.svg',title:'A clear process',caption:'A professional journey presented with clarity and care.'}],
 testimonials:[{quote:'Approved client review can be added here.',name:'Review placeholder',context:'Replace only with a verified, permissioned review.'},{quote:'A second approved review can be added here.',name:'Review placeholder',context:'Replace only with a verified, permissioned review.'}],
 faq:[['How do I schedule a consultation?','Use the consultation form or the verified contact details provided by the practice.'],['What happens during an initial consultation?','The first meeting can focus on understanding your concerns, background, goals, and whether the practice is an appropriate fit.'],['Are consultations confidential?','Professional confidentiality generally applies, subject to applicable law, professional standards, and relevant exceptions.'],['Can adolescents receive support?','Where adolescent services are offered, consent and participation requirements should be explained clearly to the young person and parent or guardian as applicable.']],
 contact:{phone:'[Add verified phone]',email:'[Add verified professional email]',address:'[Add verified clinic address]',bookingUrl:'',whatsappUrl:'',mapUrl:''},social:{instagram:'',linkedin:'',facebook:'',youtube:''},branding:{logo:'assets/logo.png',favicon:'assets/logo.png'},appearance:{primary:'#123d2c',sage:'#748f78',cream:'#f6f1e7',ink:'#17231e',gold:'#b99b62',radius:'18',motion:'smooth'},sectionImages:{hero:'assets/hero-clean.jpg',about:'assets/bg-about.svg',services:'assets/bg-services.svg',approach:'assets/bg-approach.svg',journey:'assets/bg-journey.svg',practice:'assets/bg-practice.svg',reviews:'assets/bg-reviews.svg',faq:'assets/bg-faq.svg',contact:'assets/bg-contact.svg',cta:'assets/bg-cta.svg'}
};
