(() => {
const clone=o=>JSON.parse(JSON.stringify(o));
const merge=(a,b)=>{if(!b||typeof b!=='object')return a;for(const k of Object.keys(b)){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a};
let config=clone(SITE_CONFIG);try{const saved=JSON.parse(localStorage.getItem('poojaSiteConfig')||'null');if(saved)config=merge(config,saved)}catch(e){}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s), text=(s,v)=>{const e=$(s);if(e)e.textContent=v??''};
Object.entries(config.appearance||{}).forEach(([k,v])=>document.documentElement.style.setProperty('--'+k,v));
document.title=`${config.site.name} | ${config.site.title}`; text('#metaDescription',config.site.description); $('#metaDescription').content=config.site.description; $('#favicon').href=config.branding.favicon;
$$('[data-name]').forEach(e=>e.textContent=config.professional.name.toUpperCase()); $$('[data-title]').forEach(e=>e.textContent=config.professional.designation); text('#heroEyebrow',config.hero.eyebrow);text('#heroHeading',config.hero.heading);text('#heroHighlight',config.hero.highlight);text('#heroDescription',config.hero.description);$('#heroImage').src=config.hero.image;$('#navLogo').src=config.branding.logo;$('#footerLogo').src=config.branding.logo;text('#bio',config.professional.biography);text('#philosophy',config.philosophy);text('#qualifications',config.professional.qualifications);text('#registration',config.professional.registration);text('#experience',config.professional.experience);text('#phone',config.contact.phone);text('#email',config.contact.email);text('#address',config.contact.address);text('#footerEmail',config.contact.email);text('#footerPhone',config.contact.phone);text('#copyright',`© ${new Date().getFullYear()} ${config.professional.name}. All rights reserved.`);
const timeline=$('#timeline');(config.timeline||[]).forEach((t,i)=>timeline.insertAdjacentHTML('beforeend',`<article class="timeline-item reveal"><div class="timeline-year">${esc(t.year)}</div><div class="timeline-line"><i></i></div><div class="timeline-content"><h3>${esc(t.title)}</h3><p>${esc(t.text)}</p></div></article>`));
const services=$('#servicesGrid');(config.services||[]).forEach((s,i)=>{const el=document.createElement('article');el.className='service-card reveal';el.innerHTML=`<div class="service-top"><span>0${i+1}</span><i>↗</i></div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><button class="service-link" type="button">Explore service <span>↗</span></button>`;el.querySelector('button').onclick=()=>openService(s);services.appendChild(el)});
const steps=$('#steps');(config.approach||[]).forEach((s,i)=>{steps.insertAdjacentHTML('beforeend',`<article class="step reveal"><span>0${i+1}</span><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><b class="step-arrow">↘</b></article>`)})
const gallery=$('#galleryGrid');(config.gallery||[]).forEach(g=>{const b=document.createElement('button');b.className='gallery-item reveal';b.innerHTML=`<img src="${esc(g.image)}" alt="${esc(g.title)}" loading="lazy"><span><b>${esc(g.title)}</b><small>${esc(g.caption)}</small></span>`;b.onclick=()=>{lightboxImage.src=g.image;lightboxTitle.textContent=g.title;lightboxCaption.textContent=g.caption;open($('#lightbox'))};gallery.appendChild(b)});
const testimonials=$('#testimonialGrid');(config.testimonials||[]).forEach(t=>testimonials.insertAdjacentHTML('beforeend',`<article class="testimonial-card reveal"><span class="quote-symbol">“</span><p>${esc(t.quote)}</p><div><b>${esc(t.name)}</b><small>${esc(t.context)}</small></div></article>`));
const faq=$('#faqList');(config.faq||[]).forEach(f=>{const d=document.createElement('details');d.innerHTML=`<summary>${esc(f[0])}<span>+</span></summary><p>${esc(f[1])}</p>`;faq.appendChild(d)});
const booking=$('#bookingButton');if(config.contact.bookingUrl)booking.href=config.contact.bookingUrl;const wa=$('#whatsappButton');if(config.contact.whatsappUrl){wa.hidden=false;wa.href=config.contact.whatsappUrl}
const socials=$('#socials');Object.entries(config.social||{}).forEach(([k,v])=>{if(v){const a=document.createElement('a');a.href=v;a.target='_blank';a.rel='noopener';a.textContent=k[0].toUpperCase()+k.slice(1);socials.appendChild(a)}});
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const modal=$('#serviceModal'),lightbox=$('#lightbox'),lightboxImage=$('#lightboxImage'),lightboxTitle=$('#lightboxTitle'),lightboxCaption=$('#lightboxCaption');function open(el){el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.classList.add('locked')}function close(el){el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.classList.remove('locked')}function openService(s){text('#modalTitle',s.title);text('#modalText',s.text);text('#modalDetail',s.detail);text('#modalExpectations',s.expectations);text('#modalAudience',s.audience);open(modal)}$$('[data-close]').forEach(x=>x.onclick=()=>close(modal));$$('[data-lightbox-close]').forEach(x=>x.onclick=()=>close(lightbox));document.addEventListener('keydown',e=>{if(e.key==='Escape'){close(modal);close(lightbox)}});
const header=$('#header'),progress=$('#progress');let ticking=false;function onScroll(){const y=scrollY;header.classList.toggle('scrolled',y>30);const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max?y/max:0})`;$$('.parallax').forEach(el=>{const speed=+el.dataset.speed||.04;el.style.transform=`translate3d(0,${y*speed}px,0)`});ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(onScroll);ticking=true}});onScroll();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');observer.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -50px'});function observe(){ $$('.reveal').forEach(e=>observer.observe(e)) }observe();
const menu=$('#menuToggle'),nav=$('#nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)};$$('#nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
$('#consultationForm').addEventListener('submit',e=>{e.preventDefault();text('#formStatus','Thank you. Your request is ready to be sent through the practice’s configured contact method.');e.target.reset()});
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id.length>1){const el=$(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}}}));
})();
